raise "I can't handle this platform: #{RUBY_PLATFORM}" unless RUBY_PLATFORM =~ /darwin|linux/


file "js-1.7.0.tar.gz" => [] do
  sh 'curl -O http://ftp.mozilla.org/pub/mozilla.org/js/js-1.7.0.tar.gz'
end

file "js" => [ "js-1.7.0.tar.gz" ] do |t|
  sh 'tar zxf js-1.7.0.tar.gz'
end
  
desc "Clean up as though this were a fresh distribution"
task :dist_clean => [ :clean ] do
  sh 'rm js-1.7.0.tar.gz'
end

desc "Clean everything"
task :clean do
  sh 'rm -rf js BUILD pkg'
end

directory "BUILD"
directory "BUILD/include/js"
directory "BUILD/bin"
directory "BUILD/lib"

desc "Build Spidermonkey"
task :build => [ "js", "BUILD/include/js", "BUILD/bin", "BUILD/lib" ] do |t|
  env = "PATH=/usr/bin:/bin:/usr/sbin:/sbin ; "
  if RUBY_PLATFORM =~ /darwin/
    env << "DYLD_LIBRARY_PATH='' ; "
  end
  prefix = Dir.getwd + "/BUILD"
  Dir.chdir('js/src')
  begin
    sh "#{env} make -f Makefile.ref BUILD_OPT=1"
    cp Dir["*.h"], "../../BUILD/include/js/"
    cp Dir["*.msg"], "../../BUILD/include/js/"
    cp Dir["*.tbl"], "../../BUILD/include/js/"
    cp Dir["*_OPT.OBJ/js"], "../../BUILD/bin/"
    cp Dir["*_OPT.OBJ/*.h"], "../../BUILD/include/js"
    cp Dir["*_OPT.OBJ/jscpucfg"], "../../BUILD/bin/"
    cp Dir["*_OPT.OBJ/jskwgen"], "../../BUILD/bin/"
    cp Dir["*_OPT.OBJ/libjs.*"], "../../BUILD/lib/"
  ensure
    Dir.chdir('../..')
  end
end

require 'rake/gempackagetask'

gem_spec = Gem::Specification.new do |s|
  s.name         = 'memetic-spidermonkey'
  s.version      = '1.7.0'
  s.summary      = 'Memetic packaging of the Spidermonkey library'
  s.platform     = Gem::Platform::CURRENT
  s.authors      = ["Antony Blakey", "http://www.mozilla.org/js/spidermonkey/"]
  s.files        = FileList["Rakefile", "{BUILD,lib}/**/*"]
  s.require_path = "lib"
  s.add_dependency("memetic", "~> 1.0") 
end

desc "Create the gem"
Rake::GemPackageTask.new(gem_spec) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

directory "../../GEM_SERVER/gems/"

desc "Build the gem, move to ../../GEM_SERVER/gems/"
task :default => [ :build, :gem, "../../GEM_SERVER/gems/"] do
  sh "mv pkg/*.gem ../../GEM_SERVER/gems/"
end